### ISSUE TITLE
Homebrew installation?

### ISSUE THREAD

**Issue by Stenstromen** [passbolt/go-passbolt-cli#31]
Would it be possible to add a Homebrew (brew utility) installation option?

A new public GitHub repository needs to be created named "homebrew-tap" with a directory named "Formula".

Then the following goreleaser yaml can be added to the current .goreleaser.yml (the brews option may be outdated, not sure)

```
brews:
  - name: go-passbolt-cli
    tap:
      owner: passbolt
      name: homebrew-tap
    commit_author:
      name: passbolt
    folder: Formula
    homepage: https://github.com/passbolt/go-passbolt-cli
    description: A CLI tool to interact with Passbolt, an Open source Password Manager for teams.
```

When implemented, go-passbolt-cli can be installed issuing:
```
brew install passbolt/tap/go-passbolt-cli
```
